app/models.py
# -*- coding: UTF-8 -*-
from . import db,login_manager
from flask.ext.login import UserMixin,AnonymousUserMixin
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime
from markdown import markdown
import bleach

class Administor(db.Model,UserMixin):
	__tablename__ = 'administors'
	id = db.Column(db.Integer,primary_key=True)
	email = db.Column(db.String(64),unique=True,index=True)
	password_hash = db.Column(db.String(128))
	name = db.Column(db.String(64))
	location = db.Column(db.String(64))
	about_me = db.Column(db.Text())
	posts = db.relationship('Post',backref='author',lazy='dynamic')

	@property
	def password(self):
		raise AttributeError('不能读取密码！')
	@password.setter
	def password(self,password):
		self.password_hash = generate_password_hash(password)
	def verify_password(self,password):
		return check_password_hash(self.password_hash,password)

@login_manager.user_loader
def load_user(user_id):
	return Administor.query.get(int(user_id))

class Post(db.Model):
	__tablename__ = 'posts'
	id = db.Column(db.Integer,primary_key=True)
	title=db.Column(db.String(128),index=True)
	body = db.Column(db.Text)
	body_html = db.Column(db.Text)
	timestamp = db.Column(db.DateTime,index = True,default=datetime.utcnow)
	author_id = db.Column(db.Integer,db.ForeignKey('administors.id'))

	@staticmethod
	def on_changed_body(target,value,oldvalue,initiator):
		allowed_tags=['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p']
		target.body_html = bleach.linkify(bleach.clean(
        	markdown(value,output_format='html'),tags=allowed_tags,strip=True))
		
db.event.listen(Post.body,'set',Post.on_changed_body)

app/admin/forms.py
# -*- coding: UTF-8 -*-
from flask.ext.wtf import Form
from wtforms import StringField,PasswordField,SubmitField,BooleanField,TextAreaField
from wtforms.validators import Required, Email, Length, Regexp, EqualTo
from wtforms import ValidationError
from ..models import Administor
from flask.ext.pagedown.fields import PageDownField

class LoginForm(Form):
	email = StringField('邮 箱',validators=[Required(),Email(),Length(1,64)])
	password = PasswordField('密 码',validators=[Required()])
	remember_me = BooleanField('记住我')
	submit = SubmitField('登 录')

class PostForm(Form):
	title = StringField('',validators=[Required()])
	body = PageDownField('',validators=[Required()])
	submit = SubmitField('发布文章')

app/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.bootstrap import Bootstrap
from flask.ext.moment import Moment
from flask.ext.pagedown import PageDown
from config import config

db = SQLAlchemy()
bootstrap = Bootstrap()
moment = Moment()
pagedown = PageDown()
login_manager = LoginManager()
login_manager.login_view = 'admin.login'
login_manager.session_protection = 'strong'

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	db.init_app(app)
	bootstrap.init_app(app)
	moment.init_app(app)
	login_manager.init_app(app)
	pagedown.init_app(app)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)
	from .admin import admin as admin_blueprint
	app.register_blueprint (admin_blueprint,url_prefix='/admin')

	return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

from . import views

app/admin/views.py
# -*- coding: UTF-8 -*-
from flask import render_template,url_for,flash,redirect,request
from flask.ext.login import login_user,login_required,logout_user,current_user
from . import admin
from forms import LoginForm,PostForm
from ..models import Administor,Post
from .. import db

@admin.route('/login',methods=["GET","POST"])
def login():
	form = LoginForm()
	if form.validate_on_submit():
		administor = Administor.query.filter_by(email=form.email.data).first()
		if administor and administor.verify_password(form.password.data):
			login_user(administor,form.remember_me.data)
			return redirect(request.args.get('next') or url_for('main.index'))
		flash('用户名或密码错误')
	return render_template('admin/login.html',form = form)
@admin.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.index'))	

@admin.route('/post',methods=["GET","POST"])
@login_required
def post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data,
			body = form.body.data,
			author = current_user._get_current_object())
		db.session.add(post)
		return redirect(url_for('main.index'))
	return render_template('admin/post.html',form=form)

@admin.route('/edit-post/<int:id>',methods=["GET","POST"])
@login_required
def edit_post(id):
	post = Post.query.get_or_404(id)
	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.body = form.body.data
		db.session.add(post)
		return redirect(url_for('main.index'))
	form.title.data = post.title
	form.body.data = post.body
	return render_template('admin/post.html',form=form)

@admin.route('/moderate')
@login_required
def moderate():
	posts = Post.query.all()
	return render_template('admin/posts.html',posts=posts)

@admin.route('/delete/<int:id>')
@login_required
def delete(id):
	post = Post.query.get_or_404(id)
	db.session.delete(post)
	return redirect(url_for('admin.moderate'))

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
# -*- coding: UTF-8 -*-
from flask import render_template,request,current_app
from . import main
from ..models import Post

@main.route('/')
def index():
    page = request.args.get('page',1,int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page,per_page=current_app.config['FLASK_POSTS_PER_PAGE'],error_out=False)
    posts = pagination.items
    return render_template('index.html',posts=posts,digest=True,pagination=pagination)

@main.route('/post/<int:id>')
def post(id):
    post = Post.query.get_or_404(id)
    return render_template('post.html',posts=[post])

@main.route('/post/<title>')
def post_about(title):
    post = Post.query.filter_by(title=title).first()
    return render_template('post.html',posts=[post])

app/templates/_posts.html
{% for post in posts %}
<div class="blog-post">
	<div class="blog-head">
    <h2 class="blog-post-title"><a href="{{url_for('main.post',id=post.id)}}">{{post.title.replace('-',' ') | title }}</a></h2>
    <p class="blog-post-date">{{ moment(post.timestamp).format('MMMM Do YYYY')}}</p>
     <p class="blog-post-meta"> Post by {{post.author.email}}</p>
     </div>
    {% if digest %}
		{% if post.body_html %}
		{{post.body_html[:200] | striptags }}
		{% else %}
		{{ post.body[:200]}}
		{% endif %}
	<div class="blog-read-all"><a href="{{url_for('main.post',id=post.id)}}">阅读全文</a></div>
	{% else %}
		{% if post.body_html %}
		{{post.body_html | safe }}
		{% else %}
		{{ post.body}}
		{% endif %}
	{% endif %}
</div><!-- /.blog-post -->
{% endfor %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block head%}
{{super()}}
<link rel ="shortcut icon" href="{{url_for('static',filename='F_icon.png')}}"
  type = "image/x-icon">
<link rel ="icon" href="{{url_for('static',filename='F_icon.png')}}"
  type = "image/x-icon">
<link rel="stylesheet" href="{{url_for('static',filename='blog.css')}}">
{% endblock %}
{% block title%}Luna-Blog{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{url_for('main.index')}}">Luna-Blog</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="navbar-link" class="nav navbar-nav">
            <li><a href="{{url_for('main.index')}}">Home</a></li>
            <li><a href="{{url_for('main.post_about',title='about-me')}}">About Me</a></li>
            <li><a href="{{url_for('main.post_about',title='about-this-blog')}}">About This Blog</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{{url_for('admin.post')}}">写文章</a></li>
              <li><a href="{{url_for('admin.moderate')}}">文章管理</a></li>
              <li><a href="{{url_for('admin.logout')}}">log out</a></li>
            </ul>
          </li>
          {%else%}
            <li><a href="{{url_for('admin.login')}}">log in</a></li>
          {%endif%}          
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
{% endblock %}

{% block content %}
<div class="container">
{% for category,message in get_flashed_messages(with_categories=true) %}
<div class="alert {%if category=='message' %}alert-info{% else %}alert-{{category}}{% endif%} alert-dismissible fade in" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {{message}}
</div>
{% endfor %}
 <div class="blog-header">
      <div class="row">
      {%block page_content%} {% endblock %}
      {% block sider_bar %}
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About Luna</h4>
            <p>欢迎来到到我的Blog</p>
            <p>我是一个正在学习Python的新手，并不是一名程序员，我有我的工作。但是我非常喜欢编程，所以我利用的闲暇时间努力学习。</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
</div>

    <footer class="blog-footer">
      <p>Blog template built for <a href="http://www.bootcss.com/">Bootstrap</a> by <a href="#">@luna</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>
{%endblock%}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{moment.lang('zh-cn')}}
<script type="text/javascript">
 $(function(){
   $("#navbar-link a").each(function(index){
     $this = $(this)
     if ($this[0].href == String(window.location)){
       $this.parent().addClass('active') 
     }
   });
 });
</script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="col-sm-8 blog-main">
{% include "_posts.html" %}
  <nav>
    <ul class="pager">
      <li {% if not pagination.has_prev %}class="disabled"{% endif%}><a href="{{url_for('main.index',page=pagination.page-1)}}">Previous</a></li>
      <li {% if not pagination.has_next %}class="disabled"{% endif%}><a href="{{url_for('main.index',page=pagination.page+1)}}">Next</a></li>
    </ul>
  </nav>
</div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block page_content %}
<div class="col-sm-8 blog-main">
{% include "_posts.html" %}
</div>
{% endblock %}